// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppError = { "error_code": "IO", context: "filesystem", technical_details: string | null, } | { "error_code": "DB", context: "database", technical_details: string | null, } | { "error_code": "AI", context: "ai", technical_details: string | null, } | { "error_code": "INTERNAL", context: "internal", technical_details: string | null, };
