/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
<<<<<<< HEAD
import { Route as SplashRouteImport } from './routes/splash'
=======
>>>>>>> origin/main
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as NotesRouteRouteImport } from './routes/notes/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotesIndexRouteImport } from './routes/notes/index'
import { Route as OnboardingModelChoiceRouteImport } from './routes/onboarding/model-choice'
import { Route as NotesIdRouteImport } from './routes/notes/$id'

<<<<<<< HEAD
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
=======
>>>>>>> origin/main
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRouteRoute = NotesRouteRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotesRouteRoute,
} as any)
const OnboardingModelChoiceRoute = OnboardingModelChoiceRouteImport.update({
  id: '/model-choice',
  path: '/model-choice',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const NotesIdRoute = NotesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NotesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notes': typeof NotesRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
<<<<<<< HEAD
  '/splash': typeof SplashRoute
=======
>>>>>>> origin/main
  '/notes/$id': typeof NotesIdRoute
  '/onboarding/model-choice': typeof OnboardingModelChoiceRoute
  '/notes/': typeof NotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
<<<<<<< HEAD
  '/splash': typeof SplashRoute
=======
>>>>>>> origin/main
  '/notes/$id': typeof NotesIdRoute
  '/onboarding/model-choice': typeof OnboardingModelChoiceRoute
  '/notes': typeof NotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notes': typeof NotesRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
<<<<<<< HEAD
  '/splash': typeof SplashRoute
=======
>>>>>>> origin/main
  '/notes/$id': typeof NotesIdRoute
  '/onboarding/model-choice': typeof OnboardingModelChoiceRoute
  '/notes/': typeof NotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/notes'
    | '/onboarding'
<<<<<<< HEAD
    | '/splash'
=======
>>>>>>> origin/main
    | '/notes/$id'
    | '/onboarding/model-choice'
    | '/notes/'
  fileRoutesByTo: FileRoutesByTo
<<<<<<< HEAD
  to:
    | '/'
    | '/onboarding'
    | '/splash'
    | '/notes/$id'
    | '/onboarding/model-choice'
    | '/notes'
=======
  to: '/' | '/onboarding' | '/notes/$id' | '/onboarding/model-choice' | '/notes'
>>>>>>> origin/main
  id:
    | '__root__'
    | '/'
    | '/notes'
    | '/onboarding'
<<<<<<< HEAD
    | '/splash'
=======
>>>>>>> origin/main
    | '/notes/$id'
    | '/onboarding/model-choice'
    | '/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotesRouteRoute: typeof NotesRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
<<<<<<< HEAD
  SplashRoute: typeof SplashRoute
=======
>>>>>>> origin/main
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
<<<<<<< HEAD
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
=======
>>>>>>> origin/main
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof NotesRouteRoute
    }
    '/onboarding/model-choice': {
      id: '/onboarding/model-choice'
      path: '/model-choice'
      fullPath: '/onboarding/model-choice'
      preLoaderRoute: typeof OnboardingModelChoiceRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/notes/$id': {
      id: '/notes/$id'
      path: '/$id'
      fullPath: '/notes/$id'
      preLoaderRoute: typeof NotesIdRouteImport
      parentRoute: typeof NotesRouteRoute
    }
  }
}

interface NotesRouteRouteChildren {
  NotesIdRoute: typeof NotesIdRoute
  NotesIndexRoute: typeof NotesIndexRoute
}

const NotesRouteRouteChildren: NotesRouteRouteChildren = {
  NotesIdRoute: NotesIdRoute,
  NotesIndexRoute: NotesIndexRoute,
}

const NotesRouteRouteWithChildren = NotesRouteRoute._addFileChildren(
  NotesRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingModelChoiceRoute: typeof OnboardingModelChoiceRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingModelChoiceRoute: OnboardingModelChoiceRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotesRouteRoute: NotesRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
<<<<<<< HEAD
  SplashRoute: SplashRoute,
=======
>>>>>>> origin/main
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
